[workspace]
members = [
  "boringssl",
  "common",
  "derive",
  "wire",
]

[patch.crates-io]
kmr-derive = { path = "derive" }
kmr-common = { path = "common" }
kmr-crypto-boring = { path = "boringssl" }
kmr-wire = { path = "wire" }
